### PR TITLE
Add TurboStreamer

### PR DESCRIPTION
**Pull request by malomalo**
I updated Rails/Ruby in the process let me know if that's an issue.

### CODE REVIEW

**Comment by malomalo** [comment]
I didn't run the performance test on it, would you mind running it and attaching your results?

**Comment by malomalo** [comment]
@joshmn ^^

**Comment by joshmn** [comment]
ah shoot, sorry @malomalo — was on vacation originally and totally dropped the ball on this. shuffling through my notifications now and tried getting everything bundled and wankel/yajl is throwing a fit on my m1. i'll have to dig into it later and figure out why. if you have any pointers that could save me some google queries it'd be appreciated!

**Comment by malomalo** [comment]
do you have yajl installed via homebrew? `brew install yajl`

**Comment by joshmn** [comment]
just had to put some brain power into it 😂 `gem install wankel -- --with-opt-dir=/opt/homebrew/Cellar/yajl/2.1.0`

running meow!

**Pull request merged**
